### ISSUE TITLE
Consider units of measurement

### ISSUE THREAD

**Issue by gpruss** [SethMMorton/natsort#100]
Hi Seth,
I just stumbled over natsort and think it's great! Would it be feasible to consider units of measurement to sort something like ['1 ft', '5 in', '10 ft', '2 in']? I would really appreciate it, if you could point me in the right direction.

Cheers,
Gunnar

**Comment by SethMMorton** [comment]
This is a good question!

There would be no good, general way to implement this directly within `natsort`, but I can imagine adding functionality to make it easy for a user to do so. It would require an enhancement to the API. Something like `post_key`, which would let a user provide a function that would operate on the data *after* all the natsort transformations have been performed (rather than before, as `key` does).

I am picturing something like this:

```python
import natsorted

def unit_convert(original):
    """Function to any inches to feet."""
    # Possibly not the most elegant solution, but it demonstrates the idea
    # Look to see if a string starts with " ft", and if so convert the preceding
    # number to inches and replace " ft" with " in".
    transformed = list(original)
    for i, x in enumerate(transformed):
        # The natsort algorithm requires that strings be in even indexes and
        # numbers in odd indexes. Only look at strings, but also skip the first
        # element since there can be no number before that.
        if i == 0 or i % 2 != 0:
            continue
        if x.startswith(" ft"):
            transformed[i-1] *= 12
            transformed[i] = x.replace(" ft", " in", 1)
    return tuple(transformed)    

data = ['1 ft', '5 in', '10 ft', '2 in']
print(natsort.natsorted(data, post_key=unit_convert))
## ['2 in', '5 in', '1 ft', '10 ft']

# To show what happens under-the hood
unit_key = natsort.natsort_keygen(post_key=unit_convert)
print([unit_key(x) for x in data])
## [(2, ' in'), (5, ' in'), (12, ' in'), (120, ' in')]
``` 

This `post_key` should be easy to implement (I am open to alternative names, though).

Would you be interested in making a pull request? The easiest method would be to capture what is currently the return value of `natsort_keygen` and run that through the `post_key` if it is defined, then add `post_key` to the other appropriate public functions.

https://github.com/SethMMorton/natsort/blob/5e640c09c5b4a10b86e3419ca81c7fb81f27a9de/natsort/natsort.py#L111

Would you be interested in contributing a PR for this? If not, I will do this, but it might not be for a bit.

**Comment by SethMMorton** [comment]
# WAIT! YOU CAN DO THIS ALREADY!

I don't know what I was thinking, but adding `post_key` is unnecessary. Since this would just be a function operated on the return value of the `natsort` key, you can just operate on the output of the
`natsort` key instead. Here's how it would look (assuming the `unit_convert` implementation above).

```python
import natsort
data = ['1 ft', '5 in', '10 ft', '2 in']
natsort_key = natsort.natsort_keygen()
print(sorted(data, key=lambda x: unit_convert(natsort_key(x))))
## ['2 in', '5 in', '1 ft', '10 ft']
```
Of course, having `post_key` is a nice feature, but no need for you to wait on that if sorting by units is needed right now.

**Comment by gpruss** [comment]
That is awesome! Thanks a lot Seth.

best regards,
Gunnar

**Comment by SethMMorton** [comment]
I'm going to re-open this because I want to add an example of this to the "recipes" section of the documentation, and this will serve as my reminder.

**Comment by SethMMorton** [comment]
I've given this some thought, and I think that it is probably better to implement this as a pre-function using `key`. This example assumes you are using unsigned integers for the sorting, but it can be easily extended to floats and/or signed numbers by updating the regex. The nice thing about this method is that because regex is used it can be extended easily.

```python
import re
import natsort

# Define how each unit will be transformed
CONVERSION_MAPPING = {
        "in": 1,
        "inch": 1,
        "inches": 1,
        "ft": 12,
        "feet": 12,
        "foot": 12,
}

# This regular expression searches for numbers and units
ALL_UNITS = "|".join(CONVERSION_MAPPING.keys())
UNIT_FINDER = re.compile(r"(\d+)\s*({})".format(ALL_UNITS), re.IGNORECASE)

def unit_replacer(matchobj):
    """Given a regex match object, return a replacement string where units are modified"""
    number = matchobj.group(1)
    unit = matchobj.group(2)
    new_number = int(number) * CONVERSION_MAPPING[unit]
    return "{} in".format(new_number)

# Demo time!
data = ['1 ft', '5 in', '10 ft', '2 in']
print(natsorted.natsort(data, key=lambda x: UNIT_FINDER.sub(unit_replacer, x)))
## ['2 in', '5 in', '1 ft', '10 ft']

print([UNIT_FINDER.sub(unit_replacer, x) for x in data])
## ['12 in', '5 in', '120 in', '2 in']
```

I may expose the function I use to create the various numeric regular expressions so that users can build custom keys from that.
