### ISSUE TITLE
Strange result for specific number strings using Dutch locale

### ISSUE THREAD

**Issue by thijsvandien** [SethMMorton/natsort#109]
**Actual behavior**
Human sorting `['461761', '462166']` using the Dutch locale gives the wrong result `['462166', '461761']`.

**Expected behavior**
The result should be `['461761', '462166']`.

**Environment 1:**
 - Python 3.8.1
 - Mac OS X 10.14.6
 - `PyICU` installed
 - Locale set to `'nl_NL'`

**Environment 2:**
 - Python 3.8.0
 - Windows 7 SP1
 - `PyICU` not installed
 - Locale set to `'nl-NL'`

**Environment 3:**
 - Python 3.8.1
 - FreeBSD 12.1
 - `PyICU` not installed
 - Locale set to `'nl_NL.ISO8859-1'`

**To reproduce**
```
>>> import locale
>>> locale.setlocale(locale.LC_ALL, 'Dutch') # replace 'Dutch' as appropriate
>>> from natsort import humansorted
>>> humansorted(['461761', '462166'])
['462166', '461761']
```

**Comment by SethMMorton** [comment]
Interesting... I cannot replicate on my Linux box at work.

In your setup where `PyICU` is *not* installed, do what is the result of the following (after setting up the locale)?

```python
>>> locale.strxfrm("461761") < locale.strxfrm("462166")
```

It *should* be `True`, but if it is `False` then that is the root of the bug.

**Comment by thijsvandien** [comment]
I tried it in all three environments (in case of OS X, after uninstalling `PyICU`) and it's `True` everywhere.

**Comment by thijsvandien** [comment]
Python 3.7.4 on OS X gives the same issue, whereas Python 3.7.4 on Kali Linux doesn't, so I can confirm that Linux seems to be unaffected somehow.

**Comment by SethMMorton** [comment]
I was trying Python 3.5 when I couldn't confirm. I will try tonight on different Python versions... perhaps it is Python 3.8 specific?

**Comment by thijsvandien** [comment]
I tried some older versions and it turns out that it last worked correctly in 4.0.4 and then broke in 5.0.0.

**Comment by SethMMorton** [comment]
OK. I can replicate on my Arch Linux machine on all active versions of Python. I'll debug, report, and get this fixed.

**Comment by SethMMorton** [comment]
I have isolated the root cause, and it is... embarrassing. Well, at least I think it is.

When `LOCALE` is turned on, all input is run through a "scrubber" to remove thousands separators from numbers, and to convert locale-specific decimal points to `"."`. Regular expressions are used to perform this "scrubbing". The regex is too complicated to show here, but basically a template is created for the regex, and then the thousands separator and decimal point as returned by `locale` is injected into to regular expression. 

In my locale, the thousands separator is `","`. However, in Dutch it is `"."`, which in a regular expression matches anything. So, it was converting `"462166"` into `"46166"` and  `"461761"` into `"46761"`, hence the reversing of order. What should have been inserted was `"\."`. Ouch.

So, I am now using `re.escape` on all the text that `locale` returns before injecting into the regex, which fixes the problem.  The worst part of this is I was escaping `"."` for the decimal point, so it's not like I didn't know it needed to be done in general!

My unit tests for the regular expression that focused on making sure that the thousands separators worked correctly were only run on the English locale. Had I run them in German as well (as I do some other tests) I would have caught this. I now run them in German, as well as explicitly add the case you showed above.

**Comment by SethMMorton** [comment]
This fix has been released in `natsort` version 7.0.1.

**Comment by thijsvandien** [comment]
We all have our 'what was I thinking?' moments. Thanks for quickly getting to the bottom of this! I'm curious however, why it did not cause trouble on some Linux installs.

**Comment by SethMMorton** [comment]
I suspect that the "thousands_sep" was not being returned correctly. To validate, set your locale to Dutch and then execute

```
>>> locale.localeconv()["thousands_sep"]
```
It should return `"."` for you on a system where `natsort` was giving bad results, but `","` on systems where the bug did not manifest.

**Comment by thijsvandien** [comment]
The Linux system I tested returns an empty string, which makes some sense, because separating thousands is optional in the Netherlands. In any case, it that explains it.
