### ISSUE TITLE
Add inplace option

### ISSUE THREAD

**Issue by fhabermacher** [SethMMorton/natsort#114]
**Describe the feature or enhancement**
Add option inplace, just for convenience :-)

**Comment by SethMMorton** [comment]
This is already supported by letting a user generate a `natsort` key and pass to `list.sort()`.

- https://github.com/SethMMorton/natsort#generating-a-reusable-sorting-key-and-sorting-in-place
- https://natsort.readthedocs.io/en/master/examples.html#generating-a-natsort-key

**Comment by fhabermacher** [comment]
Good to know. Nevertheless, as an extra plus it would be nice to be able to use natsort(mylist,inplace=True) as one-line option w/o having to first create the key. Obviously just a small nice to have, not important.

**Comment by SethMMorton** [comment]
Thank you for your suggestion, but I am actually opposed to this for a few philosophical and practical reasons.

* One of my goals with designing the `natsort` API was to keep it is as close to Python's own API so that it would be familiar to users. That is why `natsorted` behaves exactly like `sorted` and has the same calling signature with the exception of the additional `alg` option. For `alg`, I chose an enum methodology because it mirrors what the `re` module does (though in hindsight I should have called it `flags` instead of `alg` to be more familiar). Adding an `inplace` option would not only break this mirroring of the built-in method, but to my knowledge there is nothing in the Python built-in functions or std lib that has such an `inplace` option. Adding this would create a small cognitive overhead to one reading code that uses it because it is outside the normal Python paradigm, which is that only methods of objects operate in-place.
* When using the `inplace` option, the return value of `natsorted` would change (it would return `None` to be consistent with other Python APIs). At best, this increases the complexity of the documentation. But I feel that being able to toggle return value type so drastically increases confusion on usage of a function and makes testing more challenging.
* The Zen of Python states there should only be one way to do something.
* With the current solution one can do it in a single line

```python
from natsort import natsort_keygen, natsort_key
from some_module import some_list

some_list.sort(key=natsort_keygen())

# If you are using all the defaults, you can use the pre-packaged `natsort_key`
some_list.sort(key=natsort_key)
```

**Comment by fhabermacher** [comment]
Convinced not with each subpoint but overall I agree, esp. with cognitive cost also.
I was not reading you carefully enough before and did not realize the natsort_keygen() can obviously be used indeed in a a single line statement not requiring further preparation, so it's very close to ideal in any way. Thanks a lot, also for the general education!

**Comment by SethMMorton** [comment]
Thank you for the suggestion again! Please do not take my disagreeableness on this particular point as a lack of openness in general to new ideas.
