### ISSUE TITLE
Sorting that involves int or strings starting with a digit and `None` are failing with `TypeError`

### ISSUE THREAD

**Issue by karfau** [SethMMorton/natsort#117]
**Describe the bug**
When one of the sorted values is `None` and another is a string starting with a digit, a `TypeError` is raised.

**Expected behavior**
I'm not sure if this is the expected behaviour of what it should be, but I couldn't find any documentation about this specific combination.

**Environment (please complete the following information):**
 - Python Version: 3.6.8 - 3.6.11
 - OS CentOS/Ubuntu and most likely others
 - If the bug involves `LOCALE` or `humansorted`: (I don't think so, not sure)
    - Is `PyICU` installed?
    - Do you have a locale set? If so, to what?

**To Reproduce**
```
Python 3.6.11 (default, Aug 17 2020, 03:29:17) 
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from natsort import natsorted
>>> natsorted(["1", None])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/karfau/.virtualenvs/backend-python3.6/lib/python3.6/site-packages/natsort-7.0.1-py3.6.egg/natsort/natsort.py", line 259, in natsorted
    return sorted(seq, reverse=reverse, key=key)
TypeError: '<' not supported between instances of 'NoneType' and 'int'
>>> natsorted([1, None])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/karfau/.virtualenvs/backend-python3.6/lib/python3.6/site-packages/natsort-7.0.1-py3.6.egg/natsort/natsort.py", line 259, in natsorted
    return sorted(seq, reverse=reverse, key=key)
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

**Comment by cl3m0** [comment]
Workaround:
```
natsort.natsorted(['1.1', None], key=lambda i : i or '')> 
[None, '1.1']

natsort.natsorted([{'name': '1'}, {'name': None}], key=lambda i: itemgetter('name')(i) or '')
> [{'name': None}, {'name': '1'}]
```

**Comment by SethMMorton** [comment]
This is the expected behavior - you get the same result for the built-in `sorted`:

```python
>>> sorted(["1", None])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```
While `natsort` does take care of comparisons between typically uncomparable types such as `str` and `int`, it does not have any special handling for `None`, primarily because it is not clear to me how it should be handled.

---

@cl3m0's workaround is good, but I would make it a bit safer with 

```python
natsort.natsorted(['1.1', None], key=lambda i : "" if i is None else '')
```
Because `i or ''` might cause `0` to be transformed into `''` which may not be desirable.

---

Do you believe there should be special handling for `None`? If so, how do you think it should look?

Personally, I think that the `key` solution is preferred over built-in special handling because I don't think everyone would agree on how `None` should be handled, but I am open to hear arguments against this.

**Comment by karfau** [comment]
What I don't understand is why it is different for strings that don't start with a digit:

While `sorted` also fails for those:
```
>>> sorted(["abc", None])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
```

`natsorted` works just fine by putting `None` first:
```
>>> from natsort import natsorted
>>> natsorted(["abc", None])
[None, 'abc']
```

Since this behavior is already in place, one could argu that putting `None` first is already the expected behavior (in some cases).

**Comment by SethMMorton** [comment]
Now THAT’s surprising. I would have expected that to fail as well. Check out the how-to debug section at https://github.com/SethMMorton/natsort#faq to look into what is happening under the hood.

**Comment by SethMMorton** [comment]
Oh, I know what's happening. Internally, any input that is not `str`, `bytes`, or an iterable falls into the "it must be numeric` bucket. So, `None` gets the same treatment that numbers get, which is to transform them into a tuple with the first element being `""` - this ensures they are consistent with the transformed shape of strings.

The example you gave did not fail because internally it ends up comparing `("abc",)` to `("", None)`, which never has to compare `None` to anything so no `TypeError` is raised.

When the string begins with a number (or you give numeric input), then both entries begin with a leading `""` so the second element gets compared, causing the issue.

```python
>>> natsort.natsort_keygen()(["1", None])
(('', 1), ('', None))
```

---

So, the fact that it currently works for strings is an accident. I could replace `None` with `-Inf` like I do for `NaN`, which would always make it get sorted to the front.

**Comment by cl3m0** [comment]
Of course you are right, `is None` should be preferred...

I expected the same behavior as for `NaN` so for me it makes totally sense to replace `None` with `-Inf`!
