### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by mgorny** [SethMMorton/natsort#128]
Could you please make a new release? We'd use 02d6e7b1f4a5461930cfc820238fda5ffdfafabd since new hypothesis now causes the tests to fail for us.

**Comment by SethMMorton** [comment]
I chose not to make a new release after those commits because the code that gets installed into a user's environment does not change - only the tests and auxiliary code changes.

Can you be more specific about what you need the `natsort` tests for, and why you can't use the `natsort` version from that commit?

**Comment by mgorny** [comment]
We enable Gentoo users to run tests while installing packages, so that they can verify that the packages will actually work in their production environments (rather than in idealized CI environment). I've presumed others would benefit from a new release too but if that's not the case I can just make a snapshot or backport this one commit.

**Comment by SethMMorton** [comment]
I'll make a release.

**Comment by SethMMorton** [comment]
`<rant>`
The reason I am/was reluctant to do so is that it seems like I am often asked by one of the linux distro maintainers to fix a problem with the tests that are a result of some testing dependency changing it's behavior (#68, #107, #108, #126). This is frustrating because I specifically pinned the dependencies for testing in `dev/requirements.txt` to avoid that scenario altogether. I realize that the distro packagers have to work with the versions in their distro, but I can't help but view it as "please update your code and make a release because we are choosing to ignore your requirements". This is why I did finally remove the pinned dependencies in eb63252f995689929c48fe79a816e53066a3d7ba so that I might catch these in testing before I get pinged by the distro maintainers. I just wish I didn't have to.
`</rant>`

I realize this is not your fault. I just felt compelled to have my feelings on this made public.

**Comment by mgorny** [comment]
Well, our feelings are to the contrary of that. We find pinned dependencies a horrible thing since it prevents our users from upgrading various Python packages. If we were to follow all the pinned dependencies, we wouldn't be able to install practically anything because some packages will be required to be in different versions by the leaf package and by the leaf package's dependencies.

**Comment by SethMMorton** [comment]
I 100% understand what you are saying, genuinely, and I actually *do* agree that pinning runtime dependencies is a bad thing. `natsort` does not do that (there are no runtime dependencies, but if there were they would not be pinned) for precisely the reasons you site - as a library `natsort` should play nice with whatever environment that it is in.

What I am specifically talking about is the *testing* dependencies. For the tests and the tests only, `natsort` depends on `pytest`, `hypothesis` and a few other `pytest` plugins. Whether the tests for `natsort` are run with `hypothesis` version A or version B will not affect how `natsort` behaves in the system at runtime. The testing dependencies are used during testing only, and `natsort` will run just fine if they do not exist in the environment at normal runtime.

Here is where my view (as a library maintainer) differs from your view (as a distro packager) - since the dependencies needed during the `natsort` tests can be discarded after running the tests, the tests for `natsort` can be run in a virtual environment so that pinned testing dependencies can be used. In fact, `natsort` comes with a `tox` configuration file to make doing this easy, and `tox` can be configured to use the system python environment as a base and then just install what is needed for the tests in the virtual environment.  Using `tox` for the tests is how I recommend that `natsort` is tested in the README. However, I realize there are myriad reasons why it is not done this way.

I'm not saying that the distro packagers should change their methodology.  In fact, I'm not even saying that the distro packaging methdology is wrong. In my view, the library maintainer's philosophy and the distro packager's philosophy are both correct but are mutually exclusive, and if I were in your shoes I would share your philosophy as well.

At the end of the day, I want to reduce work for everyone. Each new release not only creates work for me, but also for those who use `natsort` downstream. Now that 7.1.1 has been released, users will have to evaluate whether or not they need to upgrade from 7.1.0 which creates a tiny amount of work for many people. On top of that, all the distros that use `natsort` will have to create a new package for 7.1.1.

There need not be agreement between us. I think that it is cool that the various distros choose to include `natsort` in their package repos, and so in general don't mind helping out. However, over time I have found that this comes with the penalty of not being able to maintain my library exactly as I want. Such is life, and I will make peace with that.

**Comment by jose-matos** [comment]
> There need not be agreement between us. I think that it is cool that the various distros choose to include `natsort` in their package repos, and so in general don't mind helping out. However, over time I have found that this comes with the penalty of not being able to maintain my library exactly as I want. Such is life, and I will make peace with that.

As the maintainer of `natsort` in Fedora I will thank you for your work and for willingness to deal with this. :+1: 
Best regards. :-)

**Comment by mgorny** [comment]
Yes, thank you. It's really nice to talk to someone who emphasizes with our pains and doesn't reject our methodology even if he disagrees with it.
