### ISSUE TITLE
Improve os_sorted performance by avoiding `Path` roundtrips

### ISSUE THREAD

**Issue by Dobatymo** [SethMMorton/natsort#157]
**Describe the feature or enhancement**
When using `os_sorted` on a list of Path objects they are converted to string and then back to Path.

**Provide a concrete example of how the feature or enhancement will improve `natsort`**
Avoiding this roundtrip should improve performance.

**Would you be willing to submit a Pull Request for this feature?**
I am not really familiar with the library yet. It looks like the conversion here https://github.com/SethMMorton/natsort/blob/5c52a8888c2cb0c3f08192e2684851e0253b4437/natsort/natsort.py#L672 could be moved to the else branch here https://github.com/SethMMorton/natsort/blob/5c52a8888c2cb0c3f08192e2684851e0253b4437/natsort/utils.py#L898 instead

**Comment by SethMMorton** [comment]
The conversion to `str(v)` is because any type is technically allowed as input, but it must be a string or path object to be processed. Agreed that if the input is already `Path` this is extra work.

Just curious though - are you seeing a performance issue? And if so, are you sure this is the root cause of the issue?
