### ISSUE TITLE
add a mode for hexadecimal numbers

### ISSUE THREAD

**Issue by calestyo** [SethMMorton/natsort#159]
**Describe the feature or enhancement**
It would be nice if `natsort` could provide an `alg` flag to support hexadecimal numbers.

Question remains what it should consider as hex number... would it be simply any sequence of  of `[a-zA-Z0-9]`? Or would it need some delimiters. E.g. `cafe` could be a hex number or a string. `berlin` could be considered a string or the hexnumber `be` followed by the string `rlin`.

May per default any hex-like sequence and its up to the user to only provide true hex strings if desired so.
And additionally the user could provide a list of prefixes and or postfixes that denote a hexnumber as such, like `0x` and `0X` (often used a prefix) or `h` (sometimes used as postfix).

If e.g. `0x` were then given as prefix and `h` as postfix:
```
0xca
FEh
BABE
```
would be considered as the (decimal) numbers `202`, `254` and the string `"BABE" `and sorted accordingly.

**Provide a concrete example of how the feature or enhancement will improve `natsort`**
I personally would use that to sort IPv6 address literals, but I guess other use cases exist as well.

Thanks for consideration,
Chris.

**Comment by SethMMorton** [comment]
Hey there!

This is already possible without an enhancement. You can use the `key` argument to customize your sorting experience. Behold:

```py
In [1]: import natsort

In [2]: data = ["0xca", "BABE", "FEh"]

In [3]: def hexkey(x):
   ...:     try:
   ...:         if x.startswith(("0x", "0X")):
   ...:             return int(x, 16)
   ...:         elif x.endswith("h"):
   ...:             return int(x[:-1], 16)
   ...:         return x
   ...:     except (TypeError, AttributeError):
   ...:         return x
   ...: 

In [4]: natsort.natsorted(data, key=hexkey)
Out[4]: ['0xca', 'FEh', 'BABE']

In [5]: mykey = natsort.natsort_keygen(key=hexkey)

In [6]: [mykey(x) for x in data]
Out[6]: [('', 202), ('BABE',), ('', 254)]
```

The `hexkey` function is a "quick and dirty" of the spec you gave, but it demonstrates that you have a lot of control.

**Comment by calestyo** [comment]
Well first, of course on can define one’s own key, ... but I just thought it would be a nice convenience to have this as another simple flag for `natsort`’s `ns`.

Second, the above, AFAIU, doesn't do exactly same what natsort can already do with decimal numbers (where it supports several "positions" of them in a string e.g. `libfoo1-beta-1.0.0` or so.<br>
Your key works only if the whole strings are hexnumber,s but not if it’s e.g. `data=["2001:C::", "2001:AB::"]`.

But then again, as said... I'm not sure if this can be easily (and especially sanely done.

**Comment by SethMMorton** [comment]
> Second, the above, AFAIU, doesn't do exactly same what natsort can already do with decimal numbers (where it supports several "positions" of them in a string e.g. libfoo1-beta-1.0.0 or so.

Of course - I just made a quick-and-dirty example based on the given examples. With effort it could be made more robust and work for all the examples you gave.

> Well first, of course on can define one’s own key, ... but I just thought it would be a nice convenience to have this as another simple flag for natsort’s ns.

I hear you, but as a matter of policy I try to not add flags with any of the following are true:

- The behavior can be implemented easily by the user using `key`
- How the option will behave is not obvious

The reason for the former is that I don't want the list of possible `alg` options to grow so large that it is unmaintainable and it becomes daunting for the user. The reason for the latter is that when I implement something that could reasonably be expected to behave in one of several different ways I will get lots of issues filed saying that the behavior is incorrect.

For example, in the initial spec it was indicated that "BABE" should not be converted because it did not have the proper prefix or suffix. Then, the example of `data=["2001:C::", "2001:AB::"]` was given, but there is no prefix so `C` and `AB` would be left alone as strings.  

Suppose we had the string "great" - should this be converted to `("gr", 234, "t")` or be left as `"great"`?

For something like this, I imagine every user would want the spec to behave slightly differently to match their own use case, and for that reason I am more inclined to suggest that the user writes a client-side key.

As a reasonable compromise, I wouldn't mind giving an example or two of how to do this in the "examples".

**Comment by calestyo** [comment]
> but as a matter of policy I try to not add flags when any of the following are true:

Fair enough... I guess your idea about giving an example would be indeed a good solution then.

> How the option will behave is not obvious

Well that’s what I've had already written myself above :-)

> For example, in the initial spec it was indicated that "BABE" should not be converted because it did not have the proper > prefix or suffix. Then, the example of data=["2001:C::", "2001:AB::"] was given, but there is no prefix so C and AB would > be left alone as strings.
> 
> Suppose we had the string "great" - should this be converted to ("gr", 234, "t") or be left as "great"?

What one could possibly do is, that one only considers such sequences of `a-fA-F0-9` as hex digits that are somehow separated by other letters/digits (i.e. in terms of unicode).<br>
Thus `FF Q` would be a hexnumber followed by ` Q` but `FFQ` or `FFΩQ` would be the string. But of course, just as you said, it wouldn't really be clear which characters actually do separate and which not (e.g. `.`, `,` ... and similar ones sure... but what about emojis, arrows, mathematical operators, etc.).

So I guess in the end, your idea with giving a good example and explaining what exactly it does and what not, may indeed be the best way to go.

**Comment by SethMMorton** [comment]
https://github.com/SethMMorton/natsort/wiki/Examples-and-Recipes#sorting-strings-containing-hex

**Comment by calestyo** [comment]
Thanks!
