### ISSUE TITLE
Sorting ranges with ">" and "<"

### ISSUE THREAD

**Issue by SandervanNoort** [SethMMorton/natsort#32]
Is there a way to sort the list:

["<1", "1-5", "6-10.5", ">10.5"]

I did a quick thing for my code like this:

```python
import re
import natsort

def bigsmall(line):
    def replace(match):
        val = float(match.group(2))
        return "{0}".format(val + 1 if match.group(1) == ">" else val - 1)
    return re.sub(r"([<>])=?(\d+\.?\d*)", replace, line)

ranges = ["<1", "1-5", "6-10.5", ">10.5"]
print(natsort.natsorted(ranges), "default sort")
print(natsort.natsorted(ranges, key=bigsmall), "with key")
```

**Comment by SethMMorton** [comment]
This is a *really* good question, thanks! I haven't given much thought to handling `<` or `>` yet. My first instinct would be replace them with negative and positive infinity, respectively, so that they get placed at the front and end of the list, respectively. 

Can you give some more example inputs and your expected outputs?  What would happen if there were multiple elements with `<` or `>`?  What would happen with "1<6", or even "1>6"?  Or perhaps "<hello"?

It would be interesting to handle this, but right now it is not well defined enough to know how to handle "correctly".

**Comment by SethMMorton** [comment]
I've been giving this a lot of thought, and I don't believe there is a good *general* purpose solution to this, primarily because inequalities are so fuzzy (I'm open to suggestions, though).  Comparing ">6" to ">8" is difficult, because both can represent numbers greater than or equal to each other.  Even worse would be comparing "10" to ">5", because ">5" could come before or after "10", depending on how you want to interpret it.  I think the real issue is that sorting overlapping ranges is not well defined (which comes first, "5-10", or "7-9" or ">6"?).

Having said that, your particular situation seems fairly well defined.  Each of your "ranges" is non-overlapping, which makes it clear how to sort them.  Your solution works well, but the solution that I would gravitate towards is replacing `<` and `>` with infinities, as I had alluded to before.  Below is my implementation.

```python
def inequal(x):
    """Key that makes it possible to sort a string that begins with an inequality."""
    if x.startswith('<'):
        return [float('-inf'), x[1:]]
    elif x.startswith('>'):
        return [float('inf'), x[1:]]
    else:
        return [x]
```

The only advantage of this over yours that I saw was if you have a "0"...

```python
>>> ranges = ["<1", "1-5", ">10", "<0", "6-10.5", ">10.5"]
>>> natsorted(ranges, key=bigsmall)
['<1', '1-5', '6-10.5', '>10', '>10.5', '<0']
natsorted(ranges, key=inequal)
['<0', '<1', '1-5', '6-10.5', '>10', '>10.5']
```

Although this could be remedied by telling to `natsort` to account for sign...

```python
>>> from natsort import ns
>>> natsorted(ranges, key=bigsmall, alg=ns.SIGNED)
['<0', '<1', '1-5', '6-10.5', '>10', '>10.5']
```

I'll leave it up to you to decide which is better.

If this is not the type of answer you were looking for, let me know and I'll try to come up with something else.

**Comment by SethMMorton** [comment]
If this helped you, can you close the comment?

**Comment by SethMMorton** [comment]
I am reopening because this is an interesting problem and perhaps others will suggest an interesting solution.

**Comment by SethMMorton** [comment]
There is clearly not much interest in this, so I am closing.
