### ISSUE TITLE
'_' can't be right sorted in Windows

### ISSUE THREAD

**Issue by oneTaken** [SethMMorton/natsort#41]
In windows OS, I want to sorted files in a content with a natural way. But I found your code seems to be not well done in windows.  The `'_'` is sorted after number `'0-9'`. But in windows OS, the `'_'` is showed before number `'0-9'`.

**Comment by SethMMorton** [comment]
Please give specific examples of the input you are passing, the output you are getting, and the desired output.

**Comment by SethMMorton** [comment]
Just a guess, but have you tried using `alg=ns.PATH` as suggested in http://natsort.readthedocs.io/en/stable/examples.html#sort-os-generated-paths?

**Comment by SethMMorton** [comment]
It does seem that Microsoft has a custom sorting order for characters (at least for Excel) as can be seen in the [table given here](https://answers.microsoft.com/en-us/windows/forum/windows_7-files/windows-7-file-name-sort-order/b6bb0847-4b98-4f6b-85da-fe6b65516153). In this table the `_` character appears before numbers, which is not how it appears in the [ASCII table](http://www.asciitable.com/). This is why Python's `sorted` (and thus `natsorted`) places the `_` character after and not before number characters.

Having said this, it's not clear to me what the request is here. As filed, the issue simply states that `natsort` is "not well done in windows" and points out the behavior of `natsorted` compared to Windows Explorer. Is this

- a question on how to make `natsort` return the same results as Windows Explorer? 
- an enhancement request to allow the user to modify the sorting table to match Windows Explorer?
- an insult/complaint of the quality of the `natsort` module?

Whether or not it was intended, it comes off as a bit rude to file an issue on someone's library to tell them their work is not well done, and then cease all communication after they request to you to help improve the situation by giving more information.

**Comment by SethMMorton** [comment]
Do you have a suggestion for how this might be implemented? At the end of the day, the sorting order of non-alphanumeric characters is arbitrary, so unlike a modification like being case insensitive (which just users `x.lower()`) changing the sorting order to match a different table is can't be achieved with a single, simple rule.

**Comment by SethMMorton** [comment]
To follow up with my above comment - I would welcome any PR that attempts to solve this issue.

**Comment by SethMMorton** [comment]
@earonesty Do you envision the user being able to customize the translation table, or would there be pre-defined translation tables?

I think this could work by using [`str.translate()`](https://docs.python.org/3/library/stdtypes.html#str.translate) to pre-process the text before running it through the locale filter (or in place of the locale filter).

**Comment by SethMMorton** [comment]
@earonesty I went to implement this today, and I realized that the table in the link I gave above is incomplete, so I was unable to implement this solution.  Do you know where a full table exists?

Alternatively, is there an existing module or library that already exists that provides a collation function that makes strings sort like they are on NTFS?

----

** TO ANYONE INTERESTED IN HELPING.**

I would like to implement this with a new enum (`ns.WINDOWS`/`ns.W`/`ns.NTFS`)? Whatever business logic gets implemented, the entry point would be part of `string_component_transform_factory` hook (in `utils.py`). If the logic is added here (manipulators on the string values after numbers are extracted), it should "just work".

**Comment by ganego** [comment]
I got the same problem when sorting folder names, that now appear in a different order when used on Windows.  
The problem I had, was folder names with prepending 'special' characters like `! _ + -` and so on, which I expect to be sorted before the 'normal' characters like Windows Explorer does. So for example the order should be `+a, a` instead of `a, +a` (which is what is given as a sort result right now).

Regarding your question about a complete ASCII table, I could not find any.  
Some characters are forbidden, so they can be ignored, see: https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions

I put together a list of the characters found on a 'normal' western keyboard, so basically all the ASCII chars (and some from extended ASCII) in the correct order: https://i.postimg.cc/cL5hNSnd/image.png

That is: ``' - ! # $ % & ( ) , ; @ [ ] ^ _ ` { } ~ ´ € + = § ° µ 11111 aaaaa foo_0 foo0``
This is what Windows Explorer shows, which is identical to `dir /on` (dir, sort by names) on german W7.

Windows Explorer sorting seems to be different from NTFS sorting: https://devblogs.microsoft.com/oldnewthing/20050617-10/?p=35293.
If `dir` gives NTFS order (I'm not sure), then it's different: 
That is: ``! # $ % & ' ( ) + , - 11111 ; = @ aaaaa foo0 foo_0 [ ] ^ _ ` { } ~ § ° ´ µ €``

I think Explorer sorting should be used as this is what people usually see.

Hope that might be helpful.
Thank you.

**Comment by earonesty** [comment]
I would imagine `alg=ns.NTFS` or `alg=ns.WINEXPLORE`, etc. that use optional, predefined tables is the correct choice.   Arbitrary sort tables require users to develop and maintain a lot of code.... better for them to live in a public repo with an enum driving use.  With a plugin model, contributed sorting tables will improve over time.

**Comment by SethMMorton** [comment]
@ganego One of the articles you linked indicated that Windows Explorer uses the locale to sort... can you see if using `natsort` with the locale setting will replicate the results of your experiment?

**Comment by ganego** [comment]
I think the locale for Windows Explorer sorting only plays a role when going to extended-ASCII with all the special letters like äöüØ... See: https://www.ascii-code.com/  The basic-ASCII should be locale-independent.  
Sorting strings with `natsorted` like they would show up on Windows Explorer becomes an issue even with basic-ASCII signs (+ - ! ...). What I mean is: On a first issue, we could ignore locale and just set the sorting for the basic-ASCII manually if that is possible(?).

Results (W7, German):

`dir /on` (dir, sorted by name):

``' - ! # $ % & ( ) , ; @ [ ] ^ _ ` { } ~ ´ € + +11111 +aaaaa = § ° µ 11111 aaaaa foo_0 foo0``

`dir` (NTFS sorting?):
``! # $ % & ' ( ) + +11111 +aaaaa , - 11111 ; = @ aaaaa foo0 foo_0 [ ] ^ _ ` { } ~ § ° ´ µ €``

<br>

`natsorted` with Locale to German:
German_Germany.1252
['11111', "'", '-', '!', '#', '$', '%', '&', '(', ')', ',', ';', '@', '[', ']', '^', '_', '`', '{', '}', '~', '´', '€', '+', '+11111', '+aaaaa', '=', '§', '°', 'aaaaa ', 'foo0', 'foo_0', 'µ']

Without Locale:
['11111', '!', '#', '$', '%', '&', "'", '(', ')', '+', '+11111', '+aaaaa', ',', '-', ';', '=', '@', '[', ']', '^', '_', '`', 'aaaaa', 'foo0', 'foo_0', '{', '}', '~', '§', '°', '´', 'µ', '€']

Beside the obvious differences, the one thing why I sumbled upon this issue was the difference in handling of <specialChar&Letter> vs <specialChar&Number>, see the `['1', '+1', '+a', 'a']` example, where `+1` should actually be sorted in front of `1` (which would be the case for `+a` vs `a`) - no difference with locale in this example.

**Comment by SethMMorton** [comment]
I am all-in on adding this type of functionality. Having said that, I have reservations on how successful it can be:

- How could this be tested, rigorously and exhaustively?
   -  I can imagine during testing writing a C extension to access [StrCmpLogicalW](https://docs.microsoft.com/en-us/windows/win32/api/shlwapi/nf-shlwapi-strcmplogicalw) as validation, but of course this could only work on Windows.
- Is it expected that this would work on Windows only, or cross platform?
- How would this be implemented? Remember that just taking care of a subset of characters as in the suggested list above is not enough - it should really cover the whole unicode range (assuming that that is what Windows does as well)

I do not use Windows so I do not think I am in a position to implement this. But I would gladly accept a PR from the brave soul who wants to take a stab at this.

**Comment by ganego** [comment]
Well, best case: We ask MS to open-source StrCmpLogicalW...

I found this: https://gist.github.com/mcmarcu/7899295 which either uses the correct dll on Windows or on Linux some other function. Then of course you will only get "proper" Windows sorting on Windows - the question would be, do Linux users even need this? Maybe not. (But to be honest, I don't understand why a Linux user would be ok with their system sorting `1` before `!1`, as that makes absolutely no sense when `!a` is sorted before `a`, but ok).

I then found this: https://psycodedeveloper.wordpress.com/2013/04/12/c-numeric-sorting-revisited/  
It's C# and I cannot compile it, but it claims to do it like the real Windows function. I wrote a comment asking about the cases above several days ago, but it seems the blog is dead - no answer.  
In case anyone could compile it and test it, that would be nice.  

Sorting right now mostly works, except for one big issue with <specialChar&Letter> vs <specialChar&Number>. If that somehow could be fixed for the numbers that are currently sorted incorrectly.

**Comment by SethMMorton** [comment]
> Sorting right now mostly works, except for one big issue with <specialChar&Letter> vs <specialChar&Number>. 

Have you tried sorting with `ns.SIGNED`? Does that get closer to the correct results?

---

With respect to the Wordpress article: it looks like they are using a comparitor called `StringComparison.InvariantCultureIgnoreCase` which I'm pretty sure ends up using the same code internally as `StrCmpLogicalW` (https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/performing-culture-insensitive-string-comparisons). So I don't think it is actually cross-platform.

**Comment by ganego** [comment]
> Have you tried sorting with ns.SIGNED? Does that get closer to the correct results?

That won't help.

In the meantime, while looking to solve some other unrelated problem I found this:  
https://docs.python.org/3/library/pathlib.html#general-properties
>  Paths of a same flavour are comparable and orderable  

Amazing, Python comes with this built-in, and it works:
```
from pathlib import *
print( PureWindowsPath('C:\\!1') < PureWindowsPath('C:\\1') )
```
`True`


But wait! it also bugs:

```
from pathlib import *
print( PureWindowsPath('C:\\15') < PureWindowsPath('C:\\100') )
```
`False`


So while it actually perfectly sorts stuff like the problem mentioned before, it now fails at alpanumeric sorting :(  

I will open a bugreport, since this function clearly does not produce the correct order for Windows despite the name.

**Comment by SethMMorton** [comment]
> I will open a bugreport, since this function clearly does not produce the correct order for Windows despite the name.

It's your decision to file a bug report on this if you want (it's unrelated to `natsort`), but I'm not so sure it's a bug. The documentation never states that when sorted it will match Windows Explorer behavior. If I were the Python devs and had this labeled as a "bug" and not as a "feature request" I would be a bit annoyed since it is never advertised to work that way.

**Comment by SethMMorton** [comment]
OK - I have finally decided how I want to implement this.

1. I am going to introduce the functions `winsorted` and `winsort_key` into the API
2. These functions will use the Windows API directly in order to perform their actions, similar to [this answer](https://stackoverflow.com/a/48030307/1399279)
3. Because the Windows API is used, this will only be available on Windows.
4. Because the Windows API handles everything in a black-box fashion, there will be no `alg` option for customization of the results (though I will still provide `key`)

**Comment by ganego** [comment]
Good to hear.  
How will you make the error handling?  
Introduce a new error that returns when wrong OS, or simply just catch the error internally in `winsorted` and use the "old" way on Linux. I'd think the second option is a better way, since it will sort on Linux then just fine and won't crash code that someone wrote for Windows but ran on Linux. And the people using the library would not have to implement their own error exception code all the time or make switches depending on the OS themselves.

**Comment by SethMMorton** [comment]
Well, my original plan was to not even export `winsorted` on a non-windows machine. But, after I posted  my plan I realized a better solution was to instead name the function `os_sorted` (or something similar) and have it behave similar to your thought, where it sorts according to how the OS's file manager would sort.

**Comment by ganego** [comment]
That's an even more elegant solution. I like it.

**Comment by earonesty** [comment]
seems like one lambda is all you need:  `os_sorted`  ... None == don't use it.  but yeah, a key/callback type thing makes sense

**Comment by SethMMorton** [comment]
@ganego @earonesty Check out #123, which is the PR for this feature. I plan to merge sometime tomorrow. I would be open to some feedback, especially the documentation or the tests.

**Comment by ganego** [comment]
Just looked over the code but did not run any tests. Seems you used my list for the test, so if it gives the correct results I guess it works. Doc also looks ok. When will you publish a new version?

**Comment by SethMMorton** [comment]
I am trying to see if I can solve #122. If I cannot by tonight, I think I will release tonight or tomorrow.

**Comment by SethMMorton** [comment]
@ganego It's out - `natsort` 7.1.0.

**Comment by nelsonjchen** [comment]
> StrCmpLogicalW

I wonder if WINE's version is accurate.

https://github.com/wine-mirror/wine/blob/e909986e6ea5ecd49b2b847f321ad89b2ae4f6f1/dlls/kernelbase/string.c#L1302
