### ISSUE TITLE
pytest tests the installed version, not the freshly build one

### ISSUE THREAD

**Issue by yurivict** [SethMMorton/natsort#57]
natsort-5.3.1 on FreeBSD 11.1

**Comment by SethMMorton** [comment]
This was done intentionally by introducing the new `src` folder - see https://blog.ionelmc.ro/2014/05/25/python-packaging/ for the motivation for making this change. The main point is that testing against a non-installed version does not guarantee that one is testing against what gets installed.

In https://github.com/SethMMorton/natsort#how-to-run-tests I note that using [tox](https://tox.readthedocs.io/en/latest/) or [pipenv](https://github.com/pypa/pipenv) can be used to allow you to test the freshly built version as in a virtual environment.

Will this a hardship for you?

**Comment by SethMMorton** [comment]
Perhaps a better blog post to refer to is https://hynek.me/articles/testing-packaging/.

**Comment by SethMMorton** [comment]
I can also update the docs in the https://github.com/SethMMorton/natsort#how-to-run-tests section to explicitly state that just running `pytest` won't work, and the motivation for doing it this way.

**Comment by yurivict** [comment]
This isn't a hardship, just could be misleading, and feels unnatural IMO.

**Comment by SethMMorton** [comment]
I’ve been giving this a lot of thought, and I will revert to the previous (non-src) directory structure. I still believe that testing against the installed code is a safer strategy, and wish there were some way to achieve that in tox without having to have the src-based structure that makes it inconvenient to just test the code under development. 

The issue here is practicality. I random sampling of many of the most popular python libraries showed that none of them are using the src-based structure. It is impractical to demand that those who want to develop on `natsort` learn a different methodology from the rest of the python community. 

I hope to update and release this within the next 12 hours. Thank you for your input.

**Comment by SethMMorton** [comment]
The fix is included in version 5.3.2.

**Comment by yurivict** [comment]
Thank you!
