### ISSUE TITLE
Please use pytest-pycodestyle instead of pytest-pep8

### ISSUE THREAD

**Issue by yurivict** [SethMMorton/natsort#68]
```pep8``` has been renamed to ```pycodestyle```, along with their ```pytest-``` counterparts.

**Comment by SethMMorton** [comment]
Please make a pull request for this change.

**Comment by yurivict** [comment]
Sorry, I can't. I am only a maintainer of the port.
I only tried to avoid creation of the unnecessary package.

**Comment by SethMMorton** [comment]
I don’t understand why being a maintainer of the port means you cannot create a pull request. I will accept a pull request from anyone no matter their relationship to the code. I am not asking you to be a long term contributor.

**Comment by yurivict** [comment]
I have no resources to fix issues in individual projects. I also have no idea what pep8 is for. So I would have to learn first what is it for, and this isn't going to be cost effective compared to this being done by someone who added pep8 there in the first place.

**Comment by SethMMorton** [comment]
I will make this change because your reasoning sounds valid.

### Some free advice

Please keep in mind that like yourself, the developers of the libraries and tools that you are creating ports for do so in their spare time.  If there is a bug, a developer fully expects that it is on them to investigate and fix the bug.  However, when someone asks for a specific change that does not actually fix a bug and does not provide a new feature, there is often an expectation that the asker will contribute at least some of the work; if one just says "change this thing" without offering to help then it comes across like the developer owes the asker something or that the developer is working for the asker, both of which can lead to negative feelings.

I understand why there was no accompanying PR with this issue. In the future, things could go a bit more smoothly if instead of just pointing out the problem (which comes across as complaining) an explanation of the situation could be added -- something like the following:

  > Hi, can you please change `<this>` to `<that>` since `<this>` has been deprecated in favor of
  > `<that>`. I would like to help, but am just the BSD port maintainer and don't actually have enough
  > experience with python to actually make this change.

I think that it is important for maintainers of ports/packages and developers of the libraries they package to establish good relationships with each other, and a slightly less "matter-of-fact" tone when filing issues can go long way to this end.
